# Generated by Django 4.2.3 on 2023-07-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_data', to='inventorymanagement.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_order_quantity', models.IntegerField()),
                ('re_order_quantity_unit', models.CharField(max_length=20)),
                ('re_order_status', models.CharField(choices=[('order_success', 'order_success'), ('delivary_on_way', 'delivary_on_way'), ('delivary_success', 'delivary_success')], max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_data', to='inventorymanagement.inventory')),
            ],
        ),
    ]
