# Generated by Django 4.2.3 on 2023-08-03 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('customer_id', models.CharField(max_length=50)),
                ('services', models.CharField(choices=[('home_dilivary', 'home_dilivary'), ('offline_shopping', 'offline_shopping')], max_length=20)),
                ('pquantity', models.IntegerField()),
                ('pquantity_unit', models.CharField(max_length=50)),
                ('pprice', models.IntegerField(default=0)),
                ('customer_name', models.CharField(max_length=50)),
                ('total_sell', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('invoice_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.category')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.IntegerField(default=0)),
                ('paymentmethod', models.CharField(choices=[('CASH', 'cash'), ('DEBIT_CARD', 'debit_card'), ('CREADIT_CARD', 'creadit_card')], max_length=20)),
                ('paymentstetus', models.CharField(choices=[('success', 'success'), ('pending', 'pending')], max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_data', to='productbilling.invoicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_name', models.CharField(max_length=50)),
                ('financial_amount', models.IntegerField(default=0)),
                ('financialdate', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finacial1_data', to='productbilling.invoicemodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finacial2_data', to='productbilling.paymentmodel')),
            ],
        ),
    ]
