# Generated by Django 4.2.3 on 2023-08-03 07:20

from django.db import migrations, models
import django.db.models.deletion
import staffmanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('adhar_No', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('responcebility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY', 'day'), ('HYBRID', 'hybrid'), ('NIGHT', 'night')], default='day', max_length=50)),
                ('shift_timing', models.CharField(choices=[('10AM-6PM', '10AM-6PM'), ('3PM-11PM', '3PM-11PM'), ('8PM-4AM', '8PM-4AM')], default='10AM-6PM', max_length=50)),
                ('shift_change_date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffschedule', to='staffmanagement.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('description', models.TextField(max_length=500)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=staffmanagement.models.Performance.current_year, verbose_name='year')),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February '), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May '), ('JUNE', 'June '), ('JULY', 'July'), ('AUGEST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='January', max_length=50, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffperformance', to='staffmanagement.profile')),
            ],
        ),
    ]
